stages:
- build_and_test

build:
  stage: build_and_test
  tags:
  - saas-linux-small-amd64
  image: ubuntu:22.04
  before_script:
  - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata 
  - apt-get install --yes cmake build-essential libboost-system-dev libboost-test-dev libboost-program-options-dev libopencv-dev
  script:
    - cmake ./
    - make
    - make test
